In [1]:
# Supress Warnings

import warnings
warnings.filterwarnings('ignore')

In [2]:
# Import the numpy and pandas packages

import numpy as np
import pandas as pd

## Task 1: Reading and Inspection

-  ### Subtask 1.1: Import and read

Import and read the movie database. Store it in a variable called `movies`.

In [3]:
# Read the csv file using 'read_csv'

movies = pd.read_csv('movie_data.csv')
movies

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

-  ### Subtask 1.2: Inspect the dataframe

Inspect the dataframe's columns, shapes, variable types etc.

In [4]:
print(movies.columns)
print(movies.shape)
print(type(movies))
print(movies.info())
print(movies.describe())

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')
(5043, 28)
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      5024 non-null   object
 1   director_name              4939 non-null   object
 2   num_critic_for_reviews     4993 non-null   float64
 3   duration                   5028 non-null   float64
 4   director_facebook_likes    4939 non-null   float64
 5   actor_3_facebook_likes     5020 non-null   float64
 6   actor_2_name               5030 non-null   object
 7   actor_1_facebook_likes     5036 non-null   float64
 8   gross                      4159 non-null   float64
 9   genres                     5043 non-null   object
 10  actor_1_name               5036 non-null   object
 11  movie_title                5043 non-null   object
 12  num_voted_users            5043 non-null   int64
 13  cast_total_facebook_likes  5043 non-null   int64
 14  actor_3_name               5020 non-null   object
 15  facenumber_in_poster       5030 non-null   float64
 16  plot_keywords              4890 non-null   object
 17  movie_imdb_link            5043 non-null   object
 18  num_user_for_reviews       5022 non-null   float64
 19  language                   5031 non-null   object
 20  country                    5038 non-null   object
 21  content_rating             4740 non-null   object
 22  budget                     4551 non-null   float64
 23  title_year                 4935 non-null   float64
 24  actor_2_facebook_likes     5030 non-null   float64
 25  imdb_score                 5043 non-null   float64
 26  aspect_ratio               4714 non-null   float64
 27  movie_facebook_likes       5043 non-null   int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB
None
       num_critic_for_reviews     duration  director_facebook_likes  \
count             4993.000000  5028.000000              4939.000000
mean               140.194272   107.201074               686.509212
std                121.601675    25.197441              2813.328607
min                  1.000000     7.000000                 0.000000
25%                 50.000000    93.000000                 7.000000
50%                110.000000   103.000000                49.000000
75%                195.000000   118.000000               194.500000
max                813.000000   511.000000             23000.000000

       actor_3_facebook_likes  actor_1_facebook_likes         gross  \
count             5020.000000             5036.000000  4.159000e+03
mean               645.009761             6560.047061  4.846841e+07
std               1665.041728            15020.759120  6.845299e+07
min                  0.000000                0.000000  1.620000e+02
25%                133.000000              614.000000  5.340988e+06
50%                371.500000              988.000000  2.551750e+07
75%                636.000000            11000.000000  6.230944e+07
max              23000.000000           640000.000000  7.605058e+08

       num_voted_users  cast_total_facebook_likes  facenumber_in_poster  \
count     5.043000e+03                5043.000000           5030.000000
mean      8.366816e+04                9699.063851              1.371173
std       1.384853e+05               18163.799124              2.013576
min       5.000000e+00                   0.000000              0.000000
25%       8.593500e+03                1411.000000              0.000000
50%       3.435900e+04                3090.000000              1.000000
75%       9.630900e+04               13756.500000              2.000000
max       1.689764e+06              656730.000000             43.000000

       num_user_for_reviews        budget   title_year  \
count           5022.000000  4.551000e+03  4935.000000
mean             272.770808  3.975262e+07  2002.470517
std              377.982886  2.061149e+08    12.474599
min                1.000000  2.180000e+02  1916.000000
25%               65.000000  6.000000e+06  1999.000000
50%              156.000000  2.000000e+07  2005.000000
75%              326.000000  4.500000e+07  2011.000000
max             5060.000000  1.221550e+10  2016.000000

       actor_2_facebook_likes   imdb_score  aspect_ratio  movie_facebook_likes
count             5030.000000  5043.000000   4714.000000           5043.000000
mean              1651.754473     6.442138      2.220403           7525.964505
std               4042.438863     1.125116      1.385113          19320.445110
min                  0.000000     1.600000      1.180000              0.000000
25%                281.000000     5.800000      1.850000              0.000000
50%                595.000000     6.600000      2.350000            166.000000
75%                918.000000     7.200000      2.350000           3000.000000
max             137000.000000     9.500000     16.000000         349000.000000

## Task 2: Cleaning the Data

-  ### Subtask 2.1: Inspect Null values

Find out the number of Null values in all the columns and rows. Also, find the percentage of Null values in each column. Round off the percentages upto two decimal places.

In [5]:
# Write your code for column-wise null count here
print(movies.isnull().sum())

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          21
language                      12
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

In [7]:
# Write your code for row-wise null count here
print(movies.isnull().sum(axis=1))

0        0
1        0
2        0
3        0
4       14
        ..
5038     4
5039     5
5040     4
5041     2
5042     0
Length: 5043, dtype: int64

In [6]:
# Write your code for column-wise null percentages here
print(round(100*(movies.isnull().sum()/len(movies.index)),2))

color                         0.38
director_name                 2.06
num_critic_for_reviews        0.99
duration                      0.30
director_facebook_likes       2.06
actor_3_facebook_likes        0.46
actor_2_name                  0.26
actor_1_facebook_likes        0.14
gross                        17.53
genres                        0.00
actor_1_name                  0.14
movie_title                   0.00
num_voted_users               0.00
cast_total_facebook_likes     0.00
actor_3_name                  0.46
facenumber_in_poster          0.26
plot_keywords                 3.03
movie_imdb_link               0.00
num_user_for_reviews          0.42
language                      0.24
country                       0.10
content_rating                6.01
budget                        9.76
title_year                    2.14
actor_2_facebook_likes        0.26
imdb_score                    0.00
aspect_ratio                  6.52
movie_facebook_likes          0.00
dtype: float64

-  ### Subtask 2.2: Drop unecessary columns

For this assignment, you will mostly be analyzing the movies with respect to the ratings, gross collection, popularity of movies, etc. So many of the columns in this dataframe are not required. So it is advised to drop the following columns.
-  color
-  director_facebook_likes
-  actor_1_facebook_likes
-  actor_2_facebook_likes
-  actor_3_facebook_likes
-  actor_2_name
-  cast_total_facebook_likes
-  actor_3_name
-  duration
-  facenumber_in_poster
-  content_rating
-  country
-  movie_imdb_link
-  aspect_ratio
-  plot_keywords

In [7]:
# Write your code for dropping the columns here. It is advised to keep inspecting the dataframe after each set of operations 
movies=movies.drop(['color',
'director_facebook_likes',
'actor_1_facebook_likes',
'actor_2_facebook_likes',
'actor_3_facebook_likes',
'actor_2_name',
'cast_total_facebook_likes',
'actor_3_name',
'duration',
'facenumber_in_poster',
'content_rating',
'country',
'movie_imdb_link',
'aspect_ratio',
'plot_keywords'],axis=1)
movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000
4,Doug Walker,NaN,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens ...,8,NaN,NaN,NaN,NaN,7.1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Scott Smith,1.0,NaN,Comedy|Drama,Eric Mabius,Signed Sealed Delivered,629,6.0,English,NaN,2013.0,7.7,84
5039,NaN,43.0,NaN,Crime|Drama|Mystery|Thriller,Natalie Zea,The Following,73839,359.0,English,NaN,NaN,7.5,32000
5040,Benjamin Roberds,13.0,NaN,Drama|Horror|Thriller,Eva Boehnke,A Plague So Pleasant,38,3.0,English,1400.0,2013.0,6.3,16
5041,Daniel Hsia,14.0,10443.0,Comedy|Drama|Romance,Alan Ruck,Shanghai Calling,1255,9.0,English,NaN,2012.0,6.3,660
5042,Jon Gunn,43.0,85222.0,Documentary,John August,My Date with Drew,4285,84.0,English,1100.0,2004.0,6.6,456

-  ### Subtask 2.3: Drop unecessary rows using columns with high Null percentages

Now, on inspection you might notice that some columns have large percentage (greater than 5%) of Null values. Drop all the rows which have Null values for such columns.

In [8]:
# Write your code for dropping the rows here
movies=movies.drop(['budget','gross'],axis=1)
movies

,director_name,num_critic_for_reviews,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,2009.0,7.9,33000
1,Gore Verbinski,302.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,2007.0,7.1,0
2,Sam Mendes,602.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,2015.0,6.8,85000
3,Christopher Nolan,813.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,2012.0,8.5,164000
4,Doug Walker,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens ...,8,NaN,NaN,NaN,7.1,0
...,...,...,...,...,...,...,...,...,...,...,...
5038,Scott Smith,1.0,Comedy|Drama,Eric Mabius,Signed Sealed Delivered,629,6.0,English,2013.0,7.7,84
5039,NaN,43.0,Crime|Drama|Mystery|Thriller,Natalie Zea,The Following,73839,359.0,English,NaN,7.5,32000
5040,Benjamin Roberds,13.0,Drama|Horror|Thriller,Eva Boehnke,A Plague So Pleasant,38,3.0,English,2013.0,6.3,16
5041,Daniel Hsia,14.0,Comedy|Drama|Romance,Alan Ruck,Shanghai Calling,1255,9.0,English,2012.0,6.3,660
5042,Jon Gunn,43.0,Documentary,John August,My Date with Drew,4285,84.0,English,2004.0,6.6,456

-  ### Subtask 2.4: Drop unecessary rows

Some of the rows might have greater than five NaN values. Such rows aren't of much use for the analysis and hence, should be removed.

In [9]:
# Write your code for dropping the rows here
print(round(100*(movies.isnull().sum()/len(movies.index)),2))

director_name             2.06
num_critic_for_reviews    0.99
genres                    0.00
actor_1_name              0.14
movie_title               0.00
num_voted_users           0.00
num_user_for_reviews      0.42
language                  0.24
title_year                2.14
imdb_score                0.00
movie_facebook_likes      0.00
dtype: float64

## Task 3: Data Analysis

-  ### Subtask 3.1: Change the unit of columns

Convert the unit of the `budget` and `gross` columns from `$` to `million $`.

In [12]:

# Write your code for unit conversion here
# I already drop gross and budget columns so , i need to create another dataframe
movies_copy = pd.read_csv('movie_data.csv')
movies_copy['budget'], movies_copy['gross'] = (movies_copy['budget'].astype(float)/1000000).round(2).astype(float),(movies_copy['gross'].astype(float)/1000000).round(2).astype(float)
movies_copy

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760.51,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309.40,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200.07,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448.13,Action|Thriller,...,2701.0,English,USA,PG-13,250.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,0.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,0.01,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,0.09,Documentary,...,84.0,English,USA,PG,0.0,2004.0,23.0,6.6,1.85,456

-  ### Subtask 3.2: Find the movies with highest profit

    1. Create a new column called `profit` which contains the difference of the two columns: `gross` and `budget`.
    2. Sort the dataframe using the `profit` column as reference.
    3. Extract the top ten profiting movies in descending order and store them in a new dataframe - `top10`

In [17]:
# Write your code for creating the profit column here
movies_copy['profit'] = movies_copy['gross'] - movies_copy['budget']
movies_copy

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,profit
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760.51,Action|Adventure|Fantasy|Sci-Fi,...,English,USA,PG-13,237.0,2009.0,936.0,7.9,1.78,33000,523.51
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309.40,Action|Adventure|Fantasy,...,English,USA,PG-13,300.0,2007.0,5000.0,7.1,2.35,0,9.40
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200.07,Action|Adventure|Thriller,...,English,UK,PG-13,245.0,2015.0,393.0,6.8,2.35,85000,-44.93
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448.13,Action|Thriller,...,English,USA,PG-13,250.0,2012.0,23000.0,8.5,2.35,164000,198.13
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84,NaN
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000,NaN
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,English,USA,NaN,0.0,2013.0,0.0,6.3,NaN,16,NaN
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,0.01,Comedy|Drama|Romance,...,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660,NaN
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,0.09,Documentary,...,English,USA,PG,0.0,2004.0,23.0,6.6,1.85,456,0.09

In [19]:
# Write your code for sorting the dataframe here
movies_copy =  movies_copy.sort_values(by='profit',ascending=False)
movies_copy

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,profit
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760.51,Action|Adventure|Fantasy|Sci-Fi,...,English,USA,PG-13,237.0,2009.0,936.0,7.9,1.78,33000,523.51
29,Color,Colin Trevorrow,644.0,124.0,365.0,1000.0,Judy Greer,3000.0,652.18,Action|Adventure|Sci-Fi|Thriller,...,English,USA,PG-13,150.0,2015.0,2000.0,7.0,2.00,150000,502.18
26,Color,James Cameron,315.0,194.0,0.0,794.0,Kate Winslet,29000.0,658.67,Drama|Romance,...,English,USA,PG-13,200.0,1997.0,14000.0,7.7,2.35,26000,458.67
3024,Color,George Lucas,282.0,125.0,0.0,504.0,Peter Cushing,11000.0,460.94,Action|Adventure|Fantasy|Sci-Fi,...,English,USA,PG,11.0,1977.0,1000.0,8.7,2.35,33000,449.94
3080,Color,Steven Spielberg,215.0,120.0,14000.0,548.0,Dee Wallace,861.0,434.95,Family|Sci-Fi,...,English,USA,PG,10.5,1982.0,725.0,7.9,1.85,34000,424.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5036,Color,Anthony Vallone,NaN,84.0,2.0,2.0,John Considine,45.0,NaN,Crime|Drama,...,English,USA,PG-13,0.0,2005.0,44.0,7.8,NaN,4,NaN
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84,NaN
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000,NaN
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,English,USA,NaN,0.0,2013.0,0.0,6.3,NaN,16,NaN
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,0.01,Comedy|Drama|Romance,...,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660,NaN

In [29]:
 # Write your code to get the top 10 profiting movies here
data= [movies_copy['movie_title'].head(10),movies_copy['imdb_score'].head(10),movies_copy['profit'].head(10)]
headers = ['movie_title','imdb_score', 'profit']
top10 =  pd.concat(data, axis=1, keys=headers)
top10

                                     movie_title  imdb_score  profit
0                                        Avatar          7.9  523.51
29                               Jurassic World          7.0  502.18
26                                      Titanic          7.7  458.67
3024         Star Wars: Episode IV - A New Hope          8.7  449.94
3080                 E.T. the Extra-Terrestrial          7.9  424.45
794                                The Avengers          8.1  403.28
509                               The Lion King          8.5  377.78
240   Star Wars: Episode I - The Phantom Menace          6.5  359.54
66                              The Dark Knight          9.0  348.32
439                            The Hunger Games          7.3  330.00

-  ### Subtask 3.3: Drop duplicate values

After you found out the top 10 profiting movies, you might have notice a duplicate value. So, it seems like the dataframe has duplicate values as well. Drop the duplicate values from the dataframe and repeat `Subtask 3.2`.

In [20]:
# Write your code for dropping duplicate values here
movies_copy.drop_duplicates(inplace=True)
movies_copy.duplicated().sum()

0

In [83]:
# Write code for repeating subtask 2 here
data = [movies_copy['director_name'].head(10),movies_copy['movie_title'].head(10),movies_copy['imdb_score'].head(10),movies_copy['profit'].head(10)]
headers = ['director_name','movie_title','imdb_score', 'profit']
top10 =  pd.concat(data, axis=1, keys=headers)
top10['Rank'] = range(1,11)
top10.set_index('Rank',inplace=True)
top10

,director_name,movie_title,imdb_score,profit
Rank,,,,
1,James Cameron,Avatar,7.9,523.51
2,Colin Trevorrow,Jurassic World,7.0,502.18
3,James Cameron,Titanic,7.7,458.67
4,George Lucas,Star Wars: Episode IV - A New Hope,8.7,449.94
5,Steven Spielberg,E.T. the Extra-Terrestrial,7.9,424.45
6,Joss Whedon,The Avengers,8.1,403.28
7,Roger Allers,The Lion King,8.5,377.78
8,George Lucas,Star Wars: Episode I - The Phantom Menace,6.5,359.54
9,Christopher Nolan,The Dark Knight,9.0,348.32
10,Gary Ross,The Hunger Games,7.3,330.00

**Checkpoint 2:** You might spot two movies directed by `James Cameron` in the list.

-  ### Subtask 3.4: Find IMDb Top 250

    1. Create a new dataframe `IMDb_Top_250` and store the top 250 movies with the highest IMDb Rating (corresponding to the column: `imdb_score`). Also make sure that for all of these movies, the `num_voted_users` is greater than 25,000.
Also add a `Rank` column containing the values 1 to 250 indicating the ranks of the corresponding films.
    2. Extract all the movies in the `IMDb_Top_250` dataframe which are not in the English language and store them in a new dataframe named `Top_Foreign_Lang_Film`.

In [85]:
# Write your code for extracting the top 250 movies as per the IMDb score here. Make sure that you store it in a new dataframe 
# and name that dataframe as 'IMDb_Top_250'
IMDb_Top_250 = movies_copy.sort_values(by='imdb_score',ascending = False).head(250)
IMDb_Top_250.loc[(IMDb_Top_250.num_voted_users>25),:]
IMDb_Top_250['Rank'] = range(1,251)
IMDb_Top_250.set_index('Rank',inplace=True)
IMDb_Top_250

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,profit,genre_1,genre_2
Rank,,,,,,,,,,,,,,,,,,,,,
1,Color,John Blanchard,NaN,65.0,0.0,176.0,Andrea Martin,770.0,NaN,Comedy,...,NaN,NaN,NaN,179.0,9.5,1.33,0,NaN,Comedy,NaN
2,Color,Frank Darabont,199.0,142.0,0.0,461.0,Jeffrey DeMunn,11000.0,28.34,Crime|Drama,...,R,25.0,1994.0,745.0,9.3,1.85,108000,3.34,Crime,Drama
3,Color,Francis Ford Coppola,208.0,175.0,0.0,3000.0,Marlon Brando,14000.0,134.82,Crime|Drama,...,R,6.0,1972.0,10000.0,9.2,1.85,43000,128.82,Crime,Drama
4,NaN,John Stockwell,2.0,90.0,134.0,354.0,T.J. Storm,260000.0,NaN,Action,...,NaN,17.0,2016.0,454.0,9.1,NaN,0,NaN,Action,NaN
5,Color,NaN,53.0,55.0,NaN,2.0,Olaf Lubaszenko,20.0,0.45,Drama,...,TV-MA,NaN,NaN,3.0,9.1,1.33,0,NaN,Drama,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246,Color,Niels Arden Oplev,NaN,88.0,76.0,75.0,David Dencik,690.0,NaN,Action|Crime|Mystery|Thriller,...,NaN,NaN,NaN,94.0,8.1,NaN,22,NaN,Action,Crime
247,Black and White,David Sington,107.0,100.0,90.0,65.0,Buzz Aldrin,168.0,1.13,Documentary|History,...,PG,2.0,2007.0,142.0,8.1,1.85,0,-0.87,Documentary,History
248,Color,Gore Verbinski,271.0,143.0,563.0,1000.0,Orlando Bloom,40000.0,305.39,Action|Adventure|Fantasy,...,PG-13,140.0,2003.0,5000.0,8.1,2.35,10000,165.39,Action,Adventure
249,Color,Michael Wadleigh,53.0,215.0,14.0,136.0,Jimi Hendrix,262.0,13.30,Documentary|History|Music,...,R,0.6,1970.0,227.0,8.1,2.20,0,12.70,Documentary,History
250,Color,Wes Anderson,536.0,99.0,0.0,670.0,Tom Wilkinson,13000.0,59.07,Adventure|Comedy|Crime|Drama,...,R,25.0,2014.0,1000.0,8.1,1.37,149000,34.07,Adventure,Comedy

In [35]:
# Write your code to extract top foreign language films from 'IMDb_Top_250' here
Top_Foreign_Lang_Film = IMDb_Top_250.loc[IMDb_Top_250.language!='English']
Top_Foreign_Lang_Film

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,profit,Rank
4409,NaN,John Stockwell,2.0,90.0,134.0,354.0,T.J. Storm,260000.0,NaN,Action,...,USA,NaN,17.00,2016.0,454.0,9.1,NaN,0,NaN,4
3207,Color,NaN,53.0,55.0,NaN,2.0,Olaf Lubaszenko,20.0,0.45,Drama,...,Poland,TV-MA,NaN,NaN,3.0,9.1,1.33,0,NaN,5
2824,Color,NaN,53.0,55.0,NaN,2.0,Olaf Lubaszenko,20.0,0.45,Drama,...,Poland,TV-MA,NaN,NaN,3.0,9.1,1.33,0,NaN,6
4498,Color,Sergio Leone,181.0,142.0,0.0,24.0,Luigi Pistilli,16000.0,6.10,Western,...,Italy,Approved,1.20,1966.0,34.0,8.9,2.35,20000,4.90,13
3579,Color,NaN,10.0,55.0,NaN,5.0,Fortunato Cerlino,18.0,NaN,Crime|Drama|Thriller,...,Italy,TV-MA,NaN,NaN,9.0,8.7,1.85,0,NaN,25
4747,Black and White,Akira Kurosawa,153.0,202.0,0.0,4.0,Minoru Chiaki,304.0,0.27,Action|Adventure|Drama,...,Japan,Unrated,2.00,1954.0,8.0,8.7,1.37,11000,-1.73,27
4029,Color,Fernando Meirelles,214.0,135.0,353.0,40.0,Seu Jorge,1000.0,7.56,Crime|Drama,...,Brazil,R,3.30,2002.0,69.0,8.7,1.85,28000,4.26,28
2373,Color,Hayao Miyazaki,246.0,125.0,6000.0,7.0,Ryûnosuke Kamiki,17.0,10.05,Adventure|Animation|Family|Fantasy,...,Japan,PG,19.00,2001.0,10.0,8.6,1.85,28000,-8.95,46
3931,Color,Ron Fricke,115.0,102.0,330.0,0.0,Balinese Tari Legong Dancers,48.0,2.60,Documentary|Music,...,USA,PG-13,4.00,2011.0,0.0,8.5,2.35,26000,-1.40,54
4921,Color,Majid Majidi,46.0,89.0,373.0,27.0,Amir Farrokh Hashemian,36.0,0.93,Drama|Family,...,Iran,PG,0.18,1997.0,35.0,8.5,1.85,0,0.75,56
3870,Color,Raja Menon,39.0,130.0,6.0,12.0,Sameer Ali Khan,85.0,NaN,Action|Drama|History|Thriller|War,...,India,NaN,4.40,2016.0,26.0,8.5,2.35,10000,NaN,58
4259,Color,Florian Henckel von Donnersmarck,215.0,137.0,207.0,155.0,Ulrich Mühe,380.0,11.28,Drama|Thriller,...,Germany,R,2.00,2006.0,284.0,8.5,2.35,39000,9.28,72
1298,Black and White,Jean-Pierre Jeunet,242.0,122.0,0.0,54.0,Jamel Debbouze,326.0,33.20,Comedy|Romance,...,France,R,77.00,2001.0,326.0,8.4,2.35,39000,-43.80,79
4659,Color,Asghar Farhadi,354.0,123.0,0.0,620.0,Leila Hatami,786.0,7.10,Drama|Mystery,...,Iran,PG-13,0.50,2011.0,712.0,8.4,1.85,48000,6.60,80
2323,Color,Hayao Miyazaki,174.0,134.0,6000.0,745.0,Jada Pinkett Smith,893.0,2.30,Adventure|Animation|Fantasy,...,Japan,PG-13,2400.00,1997.0,851.0,8.4,1.85,11000,-2397.70,87
4105,Color,Chan-wook Park,305.0,120.0,0.0,38.0,Ji-tae Yu,717.0,2.18,Drama|Mystery|Thriller,...,South Korea,R,3.00,2003.0,78.0,8.4,2.35,43000,-0.82,90
2970,Color,Wolfgang Petersen,96.0,293.0,249.0,18.0,Martin Semmelrogge,362.0,11.43,Adventure|Drama|Thriller|War,...,West Germany,R,14.00,1981.0,21.0,8.4,1.85,11000,-2.57,92
3685,Color,Rakeysh Omprakash Mehra,33.0,157.0,85.0,199.0,Steven Mackintosh,397.0,2.20,Comedy|Drama|History|Romance,...,India,Not Rated,NaN,2006.0,227.0,8.4,2.35,0,NaN,93
1329,Color,S.S. Rajamouli,44.0,159.0,50.0,72.0,Anushka Shetty,218.0,6.50,Action|Adventure|Drama|Fantasy|War,...,India,NaN,18.03,2015.0,133.0,8.4,1.85,21000,-11.53,95
1133,Color,NaN,23.0,52.0,NaN,114.0,Clotilde Hesme,164.0,NaN,Drama|Fantasy|Horror|Mystery,...,France,TV-MA,NaN,NaN,116.0,8.3,16.00,17000,NaN,119
4885,Black and White,King Vidor,48.0,151.0,54.0,6.0,Renée Adorée,81.0,NaN,Drama|Romance|War,...,USA,Not Rated,0.24,1925.0,12.0,8.3,1.33,226,NaN,124
4033,Color,Thomas Vinterberg,349.0,115.0,346.0,26.0,Alexandra Rapaport,74.0,0.61,Drama,...,Denmark,R,3.80,2012.0,69.0,8.3,2.35,60000,-3.19,135
2829,Color,Oliver Hirschbiegel,192.0,178.0,101.0,471.0,Bruno Ganz,918.0,5.50,Biography|Drama|History|War,...,Germany,R,13.50,2004.0,653.0,8.3,1.85,14000,-8.00,138
2734,Black and White,Fritz Lang,260.0,145.0,756.0,18.0,Gustav Fröhlich,136.0,0.03,Drama|Sci-Fi,...,Germany,Not Rated,6.00,1927.0,23.0,8.3,1.33,12000,-5.97,141
4585,Color,Joshua Oppenheimer,248.0,96.0,50.0,0.0,Herman Koto,3.0,0.48,Biography|Crime|Documentary|History,...,UK,Not Rated,1.00,2012.0,3.0,8.2,1.85,20000,-0.52,144
4000,Color,Juan José Campanella,262.0,129.0,195.0,50.0,Soledad Villamil,827.0,20.17,Drama|Mystery|Thriller,...,Argentina,R,2.00,2009.0,88.0,8.2,2.35,33000,18.17,152
4945,Color,Amal Al-Agroobi,NaN,62.0,58.0,NaN,NaN,NaN,NaN,Documentary|Family,...,United Arab Emirates,NaN,0.12,2013.0,NaN,8.2,NaN,54,NaN,157
4160,Color,Rajkumar Hirani,15.0,144.0,124.0,327.0,Sanjay Dutt,464.0,NaN,Comedy|Drama|Romance,...,India,PG-13,120.00,2006.0,426.0,8.2,2.35,349,NaN,163
2047,Color,Hayao Miyazaki,212.0,119.0,6000.0,422.0,Blythe Danner,23000.0,4.71,Adventure|Animation|Family|Fantasy,...,Japan,PG,24.00,2004.0,713.0,8.2,1.85,13000,-19.29,164
98,Color,Hideaki Anno,1.0,120.0,28.0,12.0,Shin'ya Tsukamoto,544.0,NaN,Action|Adventure|Drama|Horror|Sci-Fi,...,Japan,NaN,NaN,2016.0,106.0,8.2,2.35,0,NaN,166
4809,Color,Ingmar Bergman,76.0,91.0,0.0,92.0,Ingrid Thulin,440.0,NaN,Drama,...,Sweden,R,0.40,1972.0,132.0,8.2,1.66,0,NaN,175
1710,Color,NaN,16.0,511.0,NaN,51.0,Ingvar Eggert Sigurðsson,147.0,NaN,Crime|Drama|Thriller,...,Iceland,NaN,NaN,NaN,63.0,8.2,16.00,0,NaN,176
3550,Color,Denis Villeneuve,226.0,139.0,777.0,58.0,Mélissa Désormeaux-Poulin,131.0,6.86,Drama|Mystery|War,...,Canada,R,6.80,2010.0,66.0,8.2,1.85,37000,0.06,180
2551,Color,Guillermo del Toro,406.0,112.0,0.0,250.0,Maribel Verdú,634.0,37.62,Drama|Fantasy|War,...,Spain,R,13.50,2006.0,269.0,8.2,1.85,27000,24.12,181
3553,Color,José Padilha,142.0,115.0,294.0,15.0,Fernanda Machado,585.0,0.01,Action|Crime|Drama|Thriller,...,Brazil,R,4.00,2007.0,39.0,8.1,1.85,11000,-3.99,192
4912,Black and White,Carl Theodor Dreyer,54.0,126.0,147.0,0.0,Sylvia Eckhausen,0.0,NaN,Drama|Fantasy,...,Denmark,Not Rated,NaN,1955.0,0.0,8.1,1.37,863,NaN,193
2830,Color,Alejandro Amenábar,157.0,125.0,448.0,93.0,Lola Dueñas,273.0,2.09,Biography|Drama|Romance,...,Spain,PG-13,10.00,2004.0,114.0,8.1,2.35,0,-7.91,194
2914,Color,Je-kyu Kang,86.0,148.0,16.0,489.0,Bin Won,717.0,1.11,Action|Drama|War,...,South Korea,R,12.80,2004.0,517.0,8.1,2.35,0,-11.69,206
4682,Color,Bernardo Bertolucci,120.0,106.0,973.0,48.0,Stefania Sandrelli,319.0,NaN,Drama,...,Italy,R,0.75,1970.0,90.0,8.1,1.66,0,NaN,208
1061,Black and White,Andrei Tarkovsky,144.0,115.0,0.0,12.0,Anatoliy Solonitsyn,29.0,NaN,Drama|Mystery|Sci-Fi,...,Soviet Union,PG,1.00,1972.0,29.0,8.1,2.35,0,NaN,212
4461,Color,Thomas Vinterberg,98.0,105.0,346.0,141.0,Paprika Steen,280.0,1.65,Drama,...,Denmark,R,1.30,1998.0,278.0,8.1,1.33,5000,0.35,219
4348,Color,Jehane Noujaim,68.0,108.0,63.0,5.0,Ahmed Hassan,161.0,NaN,Documentary|Drama|History|News,...,Egypt,Not Rated,1.50,2013.0,10.0,8.1,1.85,0,NaN,229
4267,Color,Alejandro G. Iñárritu,157.0,115.0,0.0,35.0,Jorge Salinas,85.0,5.38,Drama|Thriller,...,Mexico,R,2.00,2000.0,79.0,8.1,1.85,11000,3.38,231
3423,Color,Katsuhiro Ôtomo,150.0,124.0,78.0,4.0,Takeshi Kusao,6.0,0.44,Action|Animation|Sci-Fi,...,Japan,R,1100.00,1988.0,5.0,8.1,1.85,0,-1099.56,244
2870,Color,Niels Arden Oplev,NaN,88.0,76.0,75.0,David Dencik,690.0,NaN,Action|Crime|Mystery|Thriller,...,Sweden,NaN,NaN,NaN,94.0,8.1,NaN,22,NaN,246

**Checkpoint 3:** Can you spot `Veer-Zaara` in the dataframe?

- ### Subtask 3.5: Find the best directors

    1. Group the dataframe using the `director_name` column.
    2. Find out the top 10 directors for whom the mean of `imdb_score` is the highest and store them in a new dataframe `top10director`.

In [37]:
# Write your code for extracting the top 10 directors here
top10director = movies_copy.groupby('director_name')['imdb_score'].mean().sort_values(ascending=False).head(10)
top10director

director_name
John Blanchard      9.5
Cary Bell           8.7
Mitchell Altieri    8.7
Sadyk Sher-Niyaz    8.7
Charles Chaplin     8.6
Mike Mayhall        8.6
Damien Chazelle     8.5
Ron Fricke          8.5
Raja Menon          8.5
Majid Majidi        8.5
Name: imdb_score, dtype: float64

**Checkpoint 4:** No surprises that `Damien Chazelle` (director of Whiplash and La La Land) is in this list.

-  ### Subtask 3.6: Find popular genres

You might have noticed the `genres` column in the dataframe with all the genres of the movies seperated by a pipe (`|`). Out of all the movie genres, the first two are most significant for any film.

1. Extract the first two genres from the `genres` column and store them in two new columns: `genre_1` and `genre_2`. Some of the movies might have only one genre. In such cases, extract the single genre into both the columns, i.e. for such movies the `genre_2` will be the same as `genre_1`.
2. Group the dataframe using `genre_1` as the primary column and `genre_2` as the secondary column.
3. Find out the 5 most popular combo of genres by finding the mean of the gross values using the `gross` column and store them in a new dataframe named `PopGenre`.

In [42]:
# Write your code for extracting the first two genres of each movie here
first=movies_copy['genres'].apply(lambda x: pd.Series(x.split('|')))
movies_copy['genre_1']=first[0]
movies_copy['genre_2']=first[1]
movies_copy.loc[pd.isnull(movies['genre_2']), ['genre_2']] = movies['genre_1']
print(movies.genre_1)
print(movies.genre_2)

0            Action
1            Action
2            Action
3            Action
4       Documentary
           ...
5038         Comedy
5039          Crime
5040          Drama
5041         Comedy
5042    Documentary
Name: genre_1, Length: 5043, dtype: object
0         Adventure
1         Adventure
2         Adventure
3          Thriller
4       Documentary
           ...
5038          Drama
5039          Drama
5040         Horror
5041          Drama
5042    Documentary
Name: genre_2, Length: 5043, dtype: object

In [44]:
# Write your code for grouping the dataframe here
movies_by_segment = movies_copy.groupby(['genre_1','genre_2'])
movies_by_segment

In [46]:
# Write your code for getting the 5 most popular combo of genres here
PopGenre = movies_by_segment['gross'].mean().sort_values(ascending=False).head(5)
PopGenre

genre_1    genre_2
Family     Sci-Fi       434.950000
Adventure  Sci-Fi       228.628750
           Animation    117.049915
           Family       115.536857
Action     Adventure    108.752302
Name: gross, dtype: float64

**Checkpoint 5:** Well, as it turns out. `Family + Sci-Fi` is the most popular combo of genres out there!

-  ### Subtask 3.7: Find the critic-favorite and audience-favorite actors

    1. Create three new dataframes namely, `Meryl_Streep`, `Leo_Caprio`, and `Brad_Pitt` which contain the movies in which the actors: 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' are the lead actors. Use only the `actor_1_name` column for extraction. Also, make sure that you use the names 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' for the said extraction.
    2. Append the rows of all these dataframes and store them in a new dataframe named `Combined`.
    3. Group the combined dataframe using the `actor_1_name` column.
    4. Find the mean of the `num_critic_for_reviews` and `num_user_for_review` and identify the actors which have the highest mean.

In [71]:
# Write your code for creating three new dataframes here

# Include all movies in which Meryl_Streep is the lead
Meryl_Streep = movies.loc[(movies.actor_1_name=='Meryl Streep'),:]
Meryl_Streep

,director_name,num_critic_for_reviews,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,title_year,imdb_score,movie_facebook_likes,genre_1,genre_2
410,Nancy Meyers,187.0,Comedy|Drama|Romance,Meryl Streep,It's Complicated,69860,214.0,English,2009.0,6.6,0,Comedy,Drama
1106,Curtis Hanson,42.0,Action|Adventure|Crime|Thriller,Meryl Streep,The River Wild,32544,69.0,English,1994.0,6.3,0,Action,Adventure
1204,Nora Ephron,252.0,Biography|Drama|Romance,Meryl Streep,Julie & Julia,79264,277.0,English,2009.0,7.0,13000,Biography,Drama
1408,David Frankel,208.0,Comedy|Drama|Romance,Meryl Streep,The Devil Wears Prada,286178,631.0,English,2006.0,6.8,0,Comedy,Drama
1483,Robert Redford,227.0,Drama|Thriller|War,Meryl Streep,Lions for Lambs,41170,298.0,English,2007.0,6.2,0,Drama,Thriller
1575,Sydney Pollack,66.0,Biography|Drama|Romance,Meryl Streep,Out of Africa,52339,200.0,English,1985.0,7.2,0,Biography,Drama
1618,David Frankel,234.0,Comedy|Drama|Romance,Meryl Streep,Hope Springs,34258,178.0,English,2012.0,6.3,0,Comedy,Drama
1674,Carl Franklin,64.0,Drama,Meryl Streep,One True Thing,9283,112.0,English,1998.0,7.0,592,Drama,Drama
1752,Stephen Frears,87.0,Biography|Comedy|Drama|Music|Romance,Meryl Streep,Florence Foster Jenkins,2167,32.0,English,2016.0,7.1,0,Biography,Comedy
1925,Stephen Daldry,174.0,Drama|Romance,Meryl Streep,The Hours,102123,660.0,English,2002.0,7.6,0,Drama,Romance
2781,Phyllida Lloyd,331.0,Biography|Drama|History,Meryl Streep,The Iron Lady,82327,350.0,English,2011.0,6.4,18000,Biography,Drama
3135,Robert Altman,211.0,Comedy|Drama|Music,Meryl Streep,A Prairie Home Companion,19655,280.0,English,2006.0,6.8,683,Comedy,Drama
3641,Fred Zinnemann,38.0,Drama,Meryl Streep,Julia,6454,44.0,English,1977.0,7.4,733,Drama,Drama

In [72]:
# Include all movies in which Leo_Caprio is the lead
Leo_Caprio=movies.loc[(movies.actor_1_name=='Leonardo DiCaprio'),:]
Leo_Caprio

,director_name,num_critic_for_reviews,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,title_year,imdb_score,movie_facebook_likes,genre_1,genre_2
26,James Cameron,315.0,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,1997.0,7.7,26000,Drama,Romance
50,Baz Luhrmann,490.0,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362912,753.0,English,2013.0,7.3,115000,Drama,Romance
97,Christopher Nolan,642.0,Action|Adventure|Sci-Fi|Thriller,Leonardo DiCaprio,Inception,1468200,2803.0,English,2010.0,8.8,175000,Action,Adventure
179,Alejandro G. Iñárritu,556.0,Adventure|Drama|Thriller|Western,Leonardo DiCaprio,The Revenant,406020,1188.0,English,2015.0,8.1,190000,Adventure,Drama
257,Martin Scorsese,267.0,Biography|Drama,Leonardo DiCaprio,The Aviator,264318,799.0,English,2004.0,7.5,0,Biography,Drama
296,Quentin Tarantino,765.0,Drama|Western,Leonardo DiCaprio,Django Unchained,955174,1193.0,English,2012.0,8.5,199000,Drama,Western
307,Edward Zwick,166.0,Adventure|Drama|Thriller,Leonardo DiCaprio,Blood Diamond,400292,657.0,English,2006.0,8.0,14000,Adventure,Drama
308,Martin Scorsese,606.0,Biography|Comedy|Crime|Drama,Leonardo DiCaprio,The Wolf of Wall Street,780588,1138.0,English,2013.0,8.2,138000,Biography,Comedy
326,Martin Scorsese,233.0,Crime|Drama,Leonardo DiCaprio,Gangs of New York,314033,1166.0,English,2002.0,7.5,0,Crime,Drama
361,Martin Scorsese,352.0,Crime|Drama|Thriller,Leonardo DiCaprio,The Departed,873649,2054.0,English,2006.0,8.5,29000,Crime,Drama
452,Martin Scorsese,490.0,Mystery|Thriller,Leonardo DiCaprio,Shutter Island,786092,964.0,English,2010.0,8.1,53000,Mystery,Thriller
641,Ridley Scott,238.0,Action|Drama|Thriller,Leonardo DiCaprio,Body of Lies,174248,263.0,English,2008.0,7.1,0,Action,Drama
911,Steven Spielberg,194.0,Biography|Crime|Drama,Leonardo DiCaprio,Catch Me If You Can,525801,667.0,English,2002.0,8.0,15000,Biography,Crime
990,Danny Boyle,118.0,Adventure|Drama|Thriller,Leonardo DiCaprio,The Beach,176169,548.0,English,2000.0,6.6,0,Adventure,Drama
1114,Sam Mendes,323.0,Drama|Romance,Leonardo DiCaprio,Revolutionary Road,152591,414.0,English,2008.0,7.3,0,Drama,Romance
1422,Randall Wallace,83.0,Action|Adventure,Leonardo DiCaprio,The Man in the Iron Mask,125219,244.0,English,1998.0,6.4,0,Action,Adventure
1453,Clint Eastwood,392.0,Biography|Crime|Drama,Leonardo DiCaprio,J. Edgar,102728,279.0,English,2011.0,6.6,16000,Biography,Crime
1560,Sam Raimi,63.0,Action|Thriller|Western,Leonardo DiCaprio,The Quick and the Dead,69197,216.0,English,1995.0,6.4,0,Action,Thriller
2067,Jerry Zaks,45.0,Drama,Leonardo DiCaprio,Marvin's Room,20163,71.0,English,1996.0,6.7,1000,Drama,Drama
2757,Baz Luhrmann,106.0,Drama|Romance,Leonardo DiCaprio,Romeo + Juliet,167750,506.0,English,1996.0,6.8,10000,Drama,Romance
3476,Baz Luhrmann,490.0,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362933,753.0,English,2013.0,7.3,115000,Drama,Romance

In [70]:
# Include all movies in which Brad_Pitt is the lead
Brad_Pitt = movies.loc[(movies.actor_1_name=='Brad Pitt'),:]
Brad_Pitt

,director_name,num_critic_for_reviews,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,title_year,imdb_score,movie_facebook_likes,genre_1,genre_2
101,David Fincher,362.0,Drama|Fantasy|Romance,Brad Pitt,The Curious Case of Benjamin Button,459346,822.0,English,2008.0,7.8,23000,Drama,Fantasy
147,Wolfgang Petersen,220.0,Adventure,Brad Pitt,Troy,381672,1694.0,English,2004.0,7.2,0,Adventure,Adventure
254,Steven Soderbergh,198.0,Crime|Thriller,Brad Pitt,Ocean's Twelve,284852,627.0,English,2004.0,6.4,0,Crime,Thriller
255,Doug Liman,233.0,Action|Comedy|Crime|Romance|Thriller,Brad Pitt,Mr. & Mrs. Smith,348861,798.0,English,2005.0,6.5,0,Action,Comedy
382,Tony Scott,142.0,Action|Crime|Thriller,Brad Pitt,Spy Game,121259,361.0,English,2001.0,7.0,0,Action,Crime
400,Steven Soderbergh,186.0,Crime|Thriller,Brad Pitt,Ocean's Eleven,402645,845.0,English,2001.0,7.8,0,Crime,Thriller
470,David Ayer,406.0,Action|Drama|War,Brad Pitt,Fury,303185,701.0,English,2014.0,7.6,82000,Action,Drama
611,Jean-Jacques Annaud,76.0,Adventure|Biography|Drama|History|War,Brad Pitt,Seven Years in Tibet,96385,119.0,English,1997.0,7.0,0,Adventure,Biography
683,David Fincher,315.0,Drama,Brad Pitt,Fight Club,1347461,2968.0,English,1999.0,8.8,48000,Drama,Drama
792,Patrick Gilmore,98.0,Adventure|Animation|Comedy|Drama|Family|Fantas...,Brad Pitt,Sinbad: Legend of the Seven Seas,36144,91.0,English,2003.0,6.7,880,Adventure,Animation
940,Neil Jordan,120.0,Drama|Fantasy|Horror,Brad Pitt,Interview with the Vampire: The Vampire Chroni...,239752,406.0,English,1994.0,7.6,11000,Drama,Fantasy
1490,Terrence Malick,584.0,Drama|Fantasy,Brad Pitt,The Tree of Life,136367,975.0,English,2011.0,6.7,39000,Drama,Fantasy
1722,Andrew Dominik,273.0,Biography|Crime|Drama|History|Western,Brad Pitt,The Assassination of Jesse James by the Coward...,136104,415.0,English,2007.0,7.5,0,Biography,Crime
2204,Alejandro G. Iñárritu,285.0,Drama,Brad Pitt,Babel,243799,908.0,English,2006.0,7.5,0,Drama,Drama
2333,Angelina Jolie Pitt,131.0,Drama|Romance,Brad Pitt,By the Sea,7976,61.0,English,2015.0,5.3,0,Drama,Romance
2682,Andrew Dominik,414.0,Crime|Thriller,Brad Pitt,Killing Them Softly,111625,369.0,English,2012.0,6.2,20000,Crime,Thriller
2898,Tony Scott,122.0,Action|Crime|Drama|Romance|Thriller,Brad Pitt,True Romance,163492,460.0,English,1993.0,8.0,15000,Action,Crime
4749,Tom DiCillo,10.0,Comedy|Music|Romance,Brad Pitt,Johnny Suede,3013,24.0,English,1991.0,5.8,344,Comedy,Music

In [73]:
# Write your code for combining the three dataframes here
total = Meryl_Streep.append(Leo_Caprio).append(Brad_Pitt)
total

,director_name,num_critic_for_reviews,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,title_year,imdb_score,movie_facebook_likes,genre_1,genre_2
410,Nancy Meyers,187.0,Comedy|Drama|Romance,Meryl Streep,It's Complicated,69860,214.0,English,2009.0,6.6,0,Comedy,Drama
1106,Curtis Hanson,42.0,Action|Adventure|Crime|Thriller,Meryl Streep,The River Wild,32544,69.0,English,1994.0,6.3,0,Action,Adventure
1204,Nora Ephron,252.0,Biography|Drama|Romance,Meryl Streep,Julie & Julia,79264,277.0,English,2009.0,7.0,13000,Biography,Drama
1408,David Frankel,208.0,Comedy|Drama|Romance,Meryl Streep,The Devil Wears Prada,286178,631.0,English,2006.0,6.8,0,Comedy,Drama
1483,Robert Redford,227.0,Drama|Thriller|War,Meryl Streep,Lions for Lambs,41170,298.0,English,2007.0,6.2,0,Drama,Thriller
1575,Sydney Pollack,66.0,Biography|Drama|Romance,Meryl Streep,Out of Africa,52339,200.0,English,1985.0,7.2,0,Biography,Drama
1618,David Frankel,234.0,Comedy|Drama|Romance,Meryl Streep,Hope Springs,34258,178.0,English,2012.0,6.3,0,Comedy,Drama
1674,Carl Franklin,64.0,Drama,Meryl Streep,One True Thing,9283,112.0,English,1998.0,7.0,592,Drama,Drama
1752,Stephen Frears,87.0,Biography|Comedy|Drama|Music|Romance,Meryl Streep,Florence Foster Jenkins,2167,32.0,English,2016.0,7.1,0,Biography,Comedy
1925,Stephen Daldry,174.0,Drama|Romance,Meryl Streep,The Hours,102123,660.0,English,2002.0,7.6,0,Drama,Romance
2781,Phyllida Lloyd,331.0,Biography|Drama|History,Meryl Streep,The Iron Lady,82327,350.0,English,2011.0,6.4,18000,Biography,Drama
3135,Robert Altman,211.0,Comedy|Drama|Music,Meryl Streep,A Prairie Home Companion,19655,280.0,English,2006.0,6.8,683,Comedy,Drama
3641,Fred Zinnemann,38.0,Drama,Meryl Streep,Julia,6454,44.0,English,1977.0,7.4,733,Drama,Drama
26,James Cameron,315.0,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,1997.0,7.7,26000,Drama,Romance
50,Baz Luhrmann,490.0,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362912,753.0,English,2013.0,7.3,115000,Drama,Romance
97,Christopher Nolan,642.0,Action|Adventure|Sci-Fi|Thriller,Leonardo DiCaprio,Inception,1468200,2803.0,English,2010.0,8.8,175000,Action,Adventure
179,Alejandro G. Iñárritu,556.0,Adventure|Drama|Thriller|Western,Leonardo DiCaprio,The Revenant,406020,1188.0,English,2015.0,8.1,190000,Adventure,Drama
257,Martin Scorsese,267.0,Biography|Drama,Leonardo DiCaprio,The Aviator,264318,799.0,English,2004.0,7.5,0,Biography,Drama
296,Quentin Tarantino,765.0,Drama|Western,Leonardo DiCaprio,Django Unchained,955174,1193.0,English,2012.0,8.5,199000,Drama,Western
307,Edward Zwick,166.0,Adventure|Drama|Thriller,Leonardo DiCaprio,Blood Diamond,400292,657.0,English,2006.0,8.0,14000,Adventure,Drama
308,Martin Scorsese,606.0,Biography|Comedy|Crime|Drama,Leonardo DiCaprio,The Wolf of Wall Street,780588,1138.0,English,2013.0,8.2,138000,Biography,Comedy
326,Martin Scorsese,233.0,Crime|Drama,Leonardo DiCaprio,Gangs of New York,314033,1166.0,English,2002.0,7.5,0,Crime,Drama
361,Martin Scorsese,352.0,Crime|Drama|Thriller,Leonardo DiCaprio,The Departed,873649,2054.0,English,2006.0,8.5,29000,Crime,Drama
452,Martin Scorsese,490.0,Mystery|Thriller,Leonardo DiCaprio,Shutter Island,786092,964.0,English,2010.0,8.1,53000,Mystery,Thriller
641,Ridley Scott,238.0,Action|Drama|Thriller,Leonardo DiCaprio,Body of Lies,174248,263.0,English,2008.0,7.1,0,Action,Drama
911,Steven Spielberg,194.0,Biography|Crime|Drama,Leonardo DiCaprio,Catch Me If You Can,525801,667.0,English,2002.0,8.0,15000,Biography,Crime
990,Danny Boyle,118.0,Adventure|Drama|Thriller,Leonardo DiCaprio,The Beach,176169,548.0,English,2000.0,6.6,0,Adventure,Drama
1114,Sam Mendes,323.0,Drama|Romance,Leonardo DiCaprio,Revolutionary Road,152591,414.0,English,2008.0,7.3,0,Drama,Romance
1422,Randall Wallace,83.0,Action|Adventure,Leonardo DiCaprio,The Man in the Iron Mask,125219,244.0,English,1998.0,6.4,0,Action,Adventure
1453,Clint Eastwood,392.0,Biography|Crime|Drama,Leonardo DiCaprio,J. Edgar,102728,279.0,English,2011.0,6.6,16000,Biography,Crime
1560,Sam Raimi,63.0,Action|Thriller|Western,Leonardo DiCaprio,The Quick and the Dead,69197,216.0,English,1995.0,6.4,0,Action,Thriller
2067,Jerry Zaks,45.0,Drama,Leonardo DiCaprio,Marvin's Room,20163,71.0,English,1996.0,6.7,1000,Drama,Drama
2757,Baz Luhrmann,106.0,Drama|Romance,Leonardo DiCaprio,Romeo + Juliet,167750,506.0,English,1996.0,6.8,10000,Drama,Romance
3476,Baz Luhrmann,490.0,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362933,753.0,English,2013.0,7.3,115000,Drama,Romance
101,David Fincher,362.0,Drama|Fantasy|Romance,Brad Pitt,The Curious Case of Benjamin Button,459346,822.0,English,2008.0,7.8,23000,Drama,Fantasy
147,Wolfgang Petersen,220.0,Adventure,Brad Pitt,Troy,381672,1694.0,English,2004.0,7.2,0,Adventure,Adventure
254,Steven Soderbergh,198.0,Crime|Thriller,Brad Pitt,Ocean's Twelve,284852,627.0,English,2004.0,6.4,0,Crime,Thriller
255,Doug Liman,233.0,Action|Comedy|Crime|Romance|Thriller,Brad Pitt,Mr. & Mrs. Smith,348861,798.0,English,2005.0,6.5,0,Action,Comedy
382,Tony Scott,142.0,Action|Crime|Thriller,Brad Pitt,Spy Game,121259,361.0,English,2001.0,7.0,0,Action,Crime
400,Steven Soderbergh,186.0,Crime|Thriller,Brad Pitt,Ocean's Eleven,402645,845.0,English,2001.0,7.8,0,Crime,Thriller
470,David Ayer,406.0,Action|Drama|War,Brad Pitt,Fury,303185,701.0,English,2014.0,7.6,82000,Action,Drama
611,Jean-Jacques Annaud,76.0,Adventure|Biography|Drama|History|War,Brad Pitt,Seven Years in Tibet,96385,119.0,English,1997.0,7.0,0,Adventure,Biography
683,David Fincher,315.0,Drama,Brad Pitt,Fight Club,1347461,2968.0,English,1999.0,8.8,48000,Drama,Drama
792,Patrick Gilmore,98.0,Adventure|Animation|Comedy|Drama|Family|Fantas...,Brad Pitt,Sinbad: Legend of the Seven Seas,36144,91.0,English,2003.0,6.7,880,Adventure,Animation
940,Neil Jordan,120.0,Drama|Fantasy|Horror,Brad Pitt,Interview with the Vampire: The Vampire Chroni...,239752,406.0,English,1994.0,7.6,11000,Drama,Fantasy
1490,Terrence Malick,584.0,Drama|Fantasy,Brad Pitt,The Tree of Life,136367,975.0,English,2011.0,6.7,39000,Drama,Fantasy
1722,Andrew Dominik,273.0,Biography|Crime|Drama|History|Western,Brad Pitt,The Assassination of Jesse James by the Coward...,136104,415.0,English,2007.0,7.5,0,Biography,Crime
2204,Alejandro G. Iñárritu,285.0,Drama,Brad Pitt,Babel,243799,908.0,English,2006.0,7.5,0,Drama,Drama
2333,Angelina Jolie Pitt,131.0,Drama|Romance,Brad Pitt,By the Sea,7976,61.0,English,2015.0,5.3,0,Drama,Romance
2682,Andrew Dominik,414.0,Crime|Thriller,Brad Pitt,Killing Them Softly,111625,369.0,English,2012.0,6.2,20000,Crime,Thriller
2898,Tony Scott,122.0,Action|Crime|Drama|Romance|Thriller,Brad Pitt,True Romance,163492,460.0,English,1993.0,8.0,15000,Action,Crime
4749,Tom DiCillo,10.0,Comedy|Music|Romance,Brad Pitt,Johnny Suede,3013,24.0,English,1991.0,5.8,344,Comedy,Music

In [74]:
# Write your code for grouping the combined dataframe here
actor= total.groupby('actor_1_name')
actor

In [79]:
# Write the code for finding the mean of critic reviews and audience reviews here
critic = actor['num_critic_for_reviews'].mean().sort_values(ascending=False)
print(critic)
print('\n')
user = actor['num_user_for_reviews'].mean().sort_values(ascending=False)
print(user)

actor_1_name
Leonardo DiCaprio    330.190476
Brad Pitt            231.944444
Meryl Streep         163.153846
Name: num_critic_for_reviews, dtype: float64


actor_1_name
Leonardo DiCaprio    914.476190
Brad Pitt            702.444444
Meryl Streep         257.307692
Name: num_user_for_reviews, dtype: float64

**Checkpoint 6:** `Leonardo` has aced both the lists!